---
- name: Deploy CodecoApp Operator
  hosts: master
  become: true
  vars:
    repo_dest: "/home/master/acm"
    image_tag: "miguelliceon/codecoapp-operator:2.0.0"
  tasks:
    - name: Deploy Codeco Operator
      command: make deploy IMG={{ image_tag }}
      args:
        chdir: "{{ repo_dest }}"
      environment:
        PATH: "/usr/local/go/bin:{{ ansible_env.PATH }}"
        KUBECONFIG: "/home/ubuntu/rke2.yaml"
  register: deploy_output
  ignore_errors: yes  # opcional: si no quieres que falle el playbook

- name: Show deployment logs
  debug:
    var: deploy_output