---
- name: Configurar workers RKE2
  hosts: workers
  become: yes

  vars:
    hostname: "{{ inventory_hostname }}"  # El nombre hosts del inventario

  tasks:
    - name: Establecer el nombre de host
      command: hostnamectl set-hostname "{{ hostname }}"

    - name: Reiniciar systemd-hostnamed
      systemd:
        name: systemd-hostnamed
        state: restarted

    # Comprobar si el archivo rke2.yaml existe
    - name: Comprobar si el archivo rke2.yaml existe
      stat:
        path: /etc/rancher/rke2/rke2.yaml
      register: rke2_config

    # Instalar RKE2 si no está instalado
    - name: Instalar RKE2 si no está instalado
      shell: curl -sfL https://get.rke2.io | INSTALL_rke2_TYPE="agent" sh -
      args:
        warn: false
      when: not rke2_config.stat.exists

    - name: Habilitar servicio rke2-agent
      systemd:
        name: rke2-agent.service
        enabled: yes

    - name: Crear directorio de configuración de RKE2
      file:
        path: /etc/rancher/rke2
        state: directory
        mode: '0755'
        recurse: yes

    # Copiar el archivo node-token desde la máquina local a la máquina remota
    - name: Copiar archivo node-token a la máquina remota
      copy:
        src: ./tokens/node-token
        dest: /tmp/node-token
        mode: '0644'

    - name: almacenar el token en una variable
      slurp:
        src: /tmp/node-token
      register: token

    - name: Crear archivo config.yaml con IP y token
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          server: https://10.0.0.100:9345 
          token: {{ token.content | b64decode }}
          cni: none
          cluster-cidr: "10.244.0.0/16"
        mode: '0644'

    - name: Iniciar servicio rke2-agent
      systemd:
        name: rke2-agent.service
        state: started
